#/!/bash

#This script uses trimmomatic to produce filtered and trimmed files
#This version is for trimming the secondary reference (assuming it's being generated by this pipeline)
#The reads are in ../parental_readfiles/name_R[12].fastq.gz

#. ../0.common/common.fnc	#load common variables, including Key1_My_cultivar_sample_name
				# and $Key1_Phred_quality_score_for_my_cultivar (default=30)

find $Key0_TopPath_Work/parental_readfiles/*.fastq.gz > readfilelist

readfile1="${Key0_TopPath_Work}/parental_readfiles/${Key1_My_cultivar_sample_name}_R1.fastq.gz"
readfile2="${Key0_TopPath_Work}/parental_readfiles/${Key1_My_cultivar_sample_name}_R2.fastq.gz"

outfile1paired="./${Key1_My_cultivar_sample_name}paired_R1.fastq.gz"
outfile2paired="./${Key1_My_cultivar_sample_name}paired_R2.fastq.gz"
outfile1unpaired="./${Key1_My_cultivar_sample_name}unpaired_R1.fastq.gz"
outfile2unpaired="./${Key1_My_cultivar_sample_name}unpaired_R2.fastq.gz"

CMD="java -jar trimmomatic-0.35.jar PE"
CMD="$CMD $readfile1 $readfile2 $outfile1paired"
CMD="$CMD $outfile1unpaired $outfile2paired $outfile2unpaired"
CMD="$CMD LEADING:15 TRAILING:15"			#trims bases from each end if qual<15. Change if desired
CMD="$CMD SLIDINGWINDOW:4:${Key1_Phred_quality_score_for_my_cultivar}"		#cutoff if quality score for sliding window
CMD="$CMD MINLEN:110"								#filter out reads<110 bp after trimming.

echo ${CMD}
eval ${CMD}

