#/!/bash

#This script uses trimmomatic to produce filtered and trimmed files
#This version is for trimming the secondary reference (assuming it's being generated by this pipeline)
#The reads are in ../parental_readfiles/name_R[12].fastq.gz

#. ../0.common/common.fnc	#load common variables, including Key1_My_cultivar_sample_name
				# and $Key1_Phred_quality_score_for_my_cultivar (default=30)

if [ `find ../parental_readfiles/* | wc -l` -eq 1 ]; then echo "statement is true"; fi 

# if parental readfiles are missing and only README present
if [ `find ../parental_readfiles/* | wc -l` -eq 1 ]; then echo "Parental readfiles are missing. Put them in ../parental_readfiles using name_R[12].fastq.gz format"

fi
