#! /bin/sh

#This script takes the .bam file generated by Bat_make_secondary_reference.sh, calls SNPs 
#and generates a consensus sequence. It puts the consensus sequence into ./secondary_reference


